input_data_path: "tests/fake_data.csv"
input_model_path: "models/model_forest.pkl"
output_predict_path: "data/processed/predict.csv"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"