input_data_path: "data/raw/heart.csv"
output_model_path: "models/model_logreg.pkl"
metric_path: "models/metrics_logreg.json"
splitting_params:
  val_size: 0.2
  random_state: 10
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
  target_col: "target"