apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ml
  labels:
    app: online-inference-ml
spec:
  containers:
    - image: l3lush/online_inference:v2
      name: online-inference-ml
      ports:
        - containerPort: 80